#!/usr/bin/env python
from tlp import DATA_PATH, VERSION
from tlp.application import App
from sys import exit, argv
from docopt import docopt


if __name__ == '__main__':
    arguments = {}

    try:
        with open(DATA_PATH + 'help') as help_file:
            arguments = docopt(help_file.read(), version=VERSION)
    except Exception as error:
        print(error.message)

    config = arguments.get('<configuration-file>') or '/etc/default/tlp'
    exit(App().start(config))
