#!/usr/bin/env python3
from signal import signal, SIGINT, SIG_DFL
from sys import exit, argv, excepthook
from tlp import DATA_PATH, VERSION
from tlp.application import App
from docopt import docopt


def install_excepthook():
    from gi.repository import Gtk
    old_hook = excepthook

    def new_hook(etype, evalue, etb):
        old_hook(etype, evalue, etb)
        while Gtk.main_level():
            Gtk.main_quit()
        exit()

    excepthook = new_hook


def parse_arguments():
    try:
        with open(DATA_PATH + 'help') as help_file:
            return docopt(help_file.read(), version=VERSION)
    except Exception as error:
        print(error.message)

    return {}


if __name__ == '__main__':
    config = parse_arguments().get('<configuration-file>') or '/etc/default/tlp'
    status = App().start(config)
    signal(SIGINT, SIG_DFL)
    exit(status)
