#!/usr/bin/env python

try:
    from tlpconfig.tlp.application import App
    from tlpconfig.tlp import DATA_PATH
except ImportError:
    from tlp.application import App
    from tlp import DATA_PATH


from sys import exit, argv
from docopt import docopt


if __name__ == '__main__':
    arguments = {}

    try:
        with open(DATA_PATH + 'help') as help_file:
            with open('VERSION') as version:
                arguments = docopt(help_file.read(), version=version.read())
    except Exception as error:
        print(error.message)

    config = arguments.get('<configuration-file>') or '/etc/default/tlp'
    exit(App().start(config))
