categories =['File System',
             'Processor and Frequency Scaling',
             'Kernel',
             'Undervolting',
             'Disks and Controllers',
             'PCI Express Bus',
             'Graphics Cards',
             'Networking',
             'Audio',
             'Drive Slot / Ultrabay',
             'Runtime Power Management',
             'USB',
             'System Start and Shutdown',
             'Wireless Radio Switch',
             'Battery Charge Thresholds',
             'Radio Device Wizard',
             'Trace Mode']
