from .runtime_power_management import RuntimePowerManagementView
from .system_start_and_shutdown import SystemStartAndShutdownView
from .undervolting import UndervoltingView
from .category import CategoryView
